layers:
  qwerty:
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - '&hml LCTRL A'
  - '&hml LALT S'
  - '&hml LGUI D'
  - '&hml LSHFT F'
  - G
  - H
  - '&hmr RSHFT J'
  - '&hmr RGUI K'
  - '&hmr RALT L'
  - '&hmr RCTL SEMI'
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - LGUI
  - LSHIFT
  - {t: ESC, h: sym}
  - {t: ENTER, h: nav}
  - SPACE
  - {t: TAB, h: RGUI}
  nav:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - {t: ▽, type: trans}
  - PREV
  - PP
  - NEXT
  - VOL UP
  - LEFT
  - DOWN
  - UP
  - RIGHT
  - {t: ▽, type: trans}
  - {t: LSHFT, h: sticky}
  - {t: LCTRL, h: sticky}
  - {t: LALT, h: sticky}
  - {t: LGUI, h: sticky}
  - VOL DN
  - HOME
  - PG DN
  - PG UP
  - END
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  sym:
  - '!'
  - '@'
  - '{'
  - '}'
  - '|'
  - '*'
  - '='
  - '>'
  - \
  - /
  - '#'
  - $
  - (
  - )
  - '`'
  - +
  - '-'
  - ''''
  - '"'
  - ':'
  - '%'
  - ^
  - '['
  - ']'
  - '~'
  - '&'
  - _
  - <
  - '>'
  - '?'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - BSPC
  - {t: ▽, type: trans}
  fun:
  - F9
  - F10
  - F11
  - F12
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - BT CLR ALL
  - F5
  - F6
  - F7
  - F8
  - Gui+ `
  - Sft+Ctl+ TAB
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Ctl+ TAB
  - {t: ▽, type: trans}
  - F1
  - F2
  - F3
  - F4
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Alt+ BSPC
  - Gui+ BSPC
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
combos:
- p: [13, 16]
  k: '&caps_word'
- p: [21, 22]
  k: LCTRL
- p: [22, 23]
  k: LALT
- p: [26, 27]
  k: RALT
- p: [27, 28]
  k: LCTRL
