file_format: "1"
id: dimetrodon
name: Dimetrodon
type: shield
url: https://github.com/ccblaisdell/zmk-config
requires: [pro_micro]
features:
  - keys
siblings:
  - dimetrodon_left
  - dimetrodon_right
